### ISSUE TITLE
"Delete all versions" not working as intended

### ISSUE THREAD

**Issue by zgrimz** [Barbarur/NovaPoint#23]
When I run the solution "Remove file versions", the log file states that it deletes versions, but when I go view the file in Sharepoint I can still see the old versions and that they're taking up storage within the site. 

Excerpts from log file:

> 2024/07/03 20:38:55 - [NPLogger] - ReportMode: True
2024/07/03 20:38:55 - [NPLogger] - DeleteAll: True
2024/07/03 20:38:55 - [NPLogger] - VersionsToKeep: 0
2024/07/03 20:38:55 - [NPLogger] - Recycle: False
2024/07/03 20:38:55 - [NPLogger] - AddAdmin: True
2024/07/03 20:38:55 - [NPLogger] - RemoveAdmin: False
2024/07/03 20:38:55 - [NPLogger] - AllSiteCollections: False
2024/07/03 20:38:55 - [NPLogger] - IncludePersonalSite: False
2024/07/03 20:38:55 - [NPLogger] - IncludeShareSite: False
2024/07/03 20:38:55 - [NPLogger] - OnlyGroupIdDefined: False
2024/07/03 20:38:55 - [NPLogger] - SiteUrl: https://[sitename].sharepoint.com/sites/archive
2024/07/03 20:38:55 - [NPLogger] - IncludeSubsites: False
2024/07/03 20:38:55 - [NPLogger] - ListOfSitesPath: 
2024/07/03 20:38:55 - [NPLogger] - AllLists: True
2024/07/03 20:38:55 - [NPLogger] - IncludeLists: False
2024/07/03 20:38:55 - [NPLogger] - IncludeLibraries: True
2024/07/03 20:38:55 - [NPLogger] - IncludeHiddenLists: False
2024/07/03 20:38:55 - [NPLogger] - IncludeSystemLists: False
2024/07/03 20:38:55 - [NPLogger] - ListTitle: 
2024/07/03 20:38:55 - [NPLogger] - FolderRelativeUrl: 

---

> 2024/07/03 20:27:24 - [RemoveFileVersionAuto] - Start processing File '3vB Mockup.psd'
2024/07/03 20:27:24 - [AppInfo] - Getting Access Token for root site https://[sitename].sharepoint.com
2024/07/03 20:27:24 - [AppInfo] - Got access token from memory
2024/07/03 20:27:24 - [AppInfo] - Access Token expiration time: 7/3/2024 9:43:31 PM +00:00
2024/07/03 20:27:24 - [RemoveFileVersionAuto] - Deleting all version '3vB Mockup.psd'

**Comment by Barbarur** [comment]
Hello @zgrimz,

Thank you for the logs.

I see you are running the solution in report mode. Report mode only produce a report but the delete action won't be executed.

Change it to action mode and versions should be deleted.

**Comment by zgrimz** [comment]
Strange, it’s set to action mode in the UI. Let me restart it and true again.

**Comment by zgrimz** [comment]
Despite restarting the application and my computer and ensuring "Action mode" is selected in the UI, the log file still states that Report mode is enabled:

> 2024/07/04 00:13:47 - [NPLogger] - ReportMode: True
2024/07/04 00:13:47 - [NPLogger] - DeleteAll: True

**Comment by Barbarur** [comment]
Thanks for the info. I see the issue.
I'll release a fix later today.

**Comment by Barbarur** [comment]
Hi @zgrimz ,

It should be resolved from version 0.7.4 released today.

**Comment by zgrimz** [comment]
Updated to 0.7.5 and sadly the same issue persists for me. Also attempted restarting my machine and uninstalling/reinstalling. 

> 2024/07/04 18:42:41 - [NPLogger] - ReportMode: True
2024/07/04 18:42:41 - [NPLogger] - DeleteAll: True
2024/07/04 18:42:41 - [NPLogger] - VersionsToKeep: 0
2024/07/04 18:42:41 - [NPLogger] - Recycle: False
2024/07/04 18:42:41 - [NPLogger] - AddAdmin: True
2024/07/04 18:42:41 - [NPLogger] - RemoveAdmin: False

**Comment by zgrimz** [comment]
Not sure why it's working now, but after another restart the log is showing "ReportMode: False" !

**Comment by zgrimz** [comment]
Confirmed it's working properly now, appreciate you fixing that so quickly!
